---
title: "single-heatmap"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{single-heatmap}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

We'll use ggalign to draw all the heatmap in
<https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html>

```{r setup}
library(ggalign)
```

```{r}
set.seed(123)
nr1 <- 4
nr2 <- 8
nr3 <- 6
nr <- nr1 + nr2 + nr3
nc1 <- 6
nc2 <- 8
nc3 <- 10
nc <- nc1 + nc2 + nc3
mat <- cbind(
  rbind(
    matrix(rnorm(nr1 * nc1, mean = 1, sd = 0.5), nrow = nr1),
    matrix(rnorm(nr2 * nc1, mean = 0, sd = 0.5), nrow = nr2),
    matrix(rnorm(nr3 * nc1, mean = 0, sd = 0.5), nrow = nr3)
  ),
  rbind(
    matrix(rnorm(nr1 * nc2, mean = 0, sd = 0.5), nrow = nr1),
    matrix(rnorm(nr2 * nc2, mean = 1, sd = 0.5), nrow = nr2),
    matrix(rnorm(nr3 * nc2, mean = 0, sd = 0.5), nrow = nr3)
  ),
  rbind(
    matrix(rnorm(nr1 * nc3, mean = 0.5, sd = 0.5), nrow = nr1),
    matrix(rnorm(nr2 * nc3, mean = 0.5, sd = 0.5), nrow = nr2),
    matrix(rnorm(nr3 * nc3, mean = 1, sd = 0.5), nrow = nr3)
  )
)
mat <- mat[sample(nr, nr), sample(nc, nc)]
rownames(mat) <- paste0("row", seq_len(nr))
colnames(mat) <- paste0("column", seq_len(nc))
```

```{r}
ggheatmap(mat) +
  scale_fill_gradient2(low = "#2600D1FF", high = "#EE3F3FFF") +
  hmanno("r", size = unit(15, "mm")) +
  align_dendro() +
  hmanno("t", size = unit(15, "mm")) +
  align_dendro() &
  theme(plot.margin = margin())
```

```{r}
ggheatmap(mat) +
  scale_fill_gradient2(low = "green", high = "red") +
  hmanno("r", size = unit(15, "mm")) +
  align_dendro() +
  hmanno("t", size = unit(15, "mm")) +
  align_dendro() &
  theme(plot.margin = margin())
```

```{r}
mat2 <- mat
mat2[1, 1] <- 100000
ggheatmap(mat2) +
  scale_fill_gradient2(
    low = "green", high = "red",
    limits = c(-2, 2),
    oob = scales::squish
  ) +
  hmanno("r", size = unit(15, "mm")) +
  align_dendro() +
  theme(axis.text.x = element_text(angle = -60, hjust = 0)) +
  hmanno("t", size = unit(15, "mm")) +
  align_dendro() &
  theme(plot.margin = margin())
```

```{r}
mat_with_na <- mat
na_index <- sample(c(TRUE, FALSE),
  nrow(mat) * ncol(mat),
  replace = TRUE, prob = c(1, 9)
)
mat_with_na[na_index] <- NA
ggheatmap(mat_with_na) +
  scale_fill_gradient2(
    low = "#2600D1FF",
    high = "#EE3F3FFF",
    na.value = "black"
  ) +
  hmanno("r", size = unit(15, "mm")) +
  align_dendro() +
  hmanno("t", size = unit(15, "mm")) +
  align_dendro() &
  theme(plot.margin = margin())
```
