---
title: "ComplexHeatmap: more examples"
output: rmarkdown::html_vignette
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r setup}
library(ggalign)
```

In this thread, We'll use `ggalign` to draw all the heatmap in
<https://jokergoo.github.io/ComplexHeatmap-reference/book/more-examples.html>. 


# Add more information for gene expression matrix
```{r fig.dim = c(12, 10)}
expr <- read_example("gene_expression.rds")
mat <- as.matrix(expr[, grep("cell", colnames(expr))])
base_mean <- rowMeans(mat)
mat_scaled <- t(apply(mat, 1, scale))
type <- gsub("s\\d+_", "", colnames(mat))

ggstack(data = mat_scaled) +
    # remove margins
    stack_active(theme = theme(plot.margin = margin())) +
    # group stack rows into 5 groups
    align_kmeans(centers = 5L) +
    # add a block plot for each group in the stack
    ggpanel(size = unit(1, "cm")) +
    geom_tile(aes(x = 1, fill = factor(.panel))) +
    scale_fill_brewer(palette = "Dark2", name = "Kmeans group") +
    scale_x_continuous(breaks = NULL, name = NULL) +
    # add a heatmap plot in the stack
    ggheatmap() +
    # Note, the x-axis of the left plot will have expansion,
    # so, there'll be some spaces between this heatmap of the left tile
    hmanno(free_spaces = "l") +
    scale_y_continuous(breaks = NULL) +
    scale_fill_viridis_c() +
    # add dendrogram for this heatmap
    hmanno("t") +
    align_dendro() +
    # add a block for the heatmap column
    ggalign(data = type, size = unit(1, "cm")) +
    geom_tile(aes(y = 1, fill = factor(value))) +
    scale_y_continuous(breaks = NULL, name = NULL) +
    scale_fill_brewer(palette = "Set1", name = "type") +
    # add another heatmap in the stack and set the heatmap body width
    ggheatmap(base_mean, width = unit(2, "cm")) +
    scale_y_continuous(breaks = NULL) +
    scale_x_continuous(name = "base mean", breaks = FALSE) +
    scale_fill_gradientn(colours = c("#2600D1FF", "white", "#EE3F3FFF")) +
    # set the active context of the heatmap to the top
    # and set the size of the top stack
    hmanno("t", size = unit(4, "cm")) +
    # add box plot in the heatmap top
    ggalign(theme = theme(plot.margin = margin(r = 3))) +
    geom_boxplot(aes(y = value, fill = factor(.extra_panel))) +
    scale_x_continuous(expand = expansion(), breaks = NULL) +
    scale_fill_brewer(palette = "Dark2", guide = "none") +
    theme(axis.title.y = element_blank()) +
    # we move into the stack layout
    stack_active() +
    # add a point plot
    ggalign(
        data = expr$length, size = unit(2, "cm"),
        theme = theme(plot.margin = margin(r = 3))
    ) +
    geom_point(aes(x = value)) +
    labs(x = "length") +
    theme(
        panel.border = element_rect(fill = NA),
        axis.text.x = element_text(angle = -60, hjust = 0)
    ) +
    # add another heatmap, and set the heatmap body width
    ggheatmap(expr$type, width = unit(2, "cm")) +
    # set the heatmap layout theme
    hmanno(theme = theme(plot.margin = margin(r = 3))) +
    scale_fill_brewer(palette = "Set3", name = "gene type") +
    scale_x_continuous(breaks = NULL, name = "gene type") +
    # add barplot in the top annotation, and remove the spaces in the y-axis
    hmanno("t", free_spaces = "lr", theme = theme(plot.margin = margin(b = 3))) +
    ggalign(limits = FALSE) +
    geom_bar(
        aes(.extra_panel, fill = factor(value)),
        position = position_fill()
    ) +
    scale_x_discrete() +
    scale_y_continuous(expand = expansion()) +
    scale_fill_brewer(palette = "Set3", name = "gene type", guide = "none")
```

# The measles vaccine heatmap
```{r fig.dim = c(12, 12)}
mat <- read_example("measles.rds")
ggheatmap(mat, filling = FALSE) +
    geom_tile(aes(fill = value), color = "white") +
    scale_fill_gradientn(
        colours = c("white", "cornflowerblue", "yellow", "red"),
        values = scales::rescale(c(0, 800, 1000, 127000), c(0, 1))
    ) +
    theme(axis.text.x = element_text(angle = -60, hjust = 0)) +
    hmanno("r") +
    align_dendro(plot_dendrogram = FALSE) +
    hmanno("t", size = unit(2, "cm")) +
    ggalign(data = rowSums) +
    geom_bar(aes(y = value), fill = "#FFE200", stat = "identity") +
    scale_y_continuous(expand = expansion()) +
    ggtitle("Measles cases in US states 1930-2001\nVaccine introduced 1961") +
    theme(plot.title = element_text(hjust = 0.5)) +
    hmanno("r", size = unit(2, "cm")) +
    ggalign(data = rowSums) +
    geom_bar(aes(x = value),
        fill = "#FFE200", stat = "identity",
        orientation = "y"
    ) +
    scale_x_continuous(expand = expansion()) +
    theme(axis.text.x = element_text(angle = -60, hjust = 0))
```

# Session information
```{r}
sessionInfo()
```
